# Generated by Django 5.1.5 on 2025-07-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tipoplan',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_personal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Personal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.direccion', verbose_name='Dirección de Instalación'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion_instalacion',
            field=models.CharField(max_length=255, verbose_name='Dirección de Instalación'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cliente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodo_fin',
            field=models.DateField(verbose_name='Periodo Fin'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodo_inicio',
            field=models.DateField(verbose_name='Periodo Inicio'),
        ),
        migrations.AlterField(
            model_name='tipoplan',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Tipo de Plan'),
        ),
    ]
