# Generated by Django 5.1.5 on 2025-07-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_pago_cliente_remove_tipoplan_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
