# Generated by Django 5.1.5 on 2025-07-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_cliente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
    ]
