# Generated by Django 5.1.5 on 2025-07-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_remove_cliente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='gracia_dias',
        ),
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.direccion', verbose_name='Dirección de Instalación'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
